apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 892915606637.dkr.ecr.us-east-1.amazonaws.com/mysql-repo-assignment2:v1.1
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: athakur28
        ports:
        - containerPort: 3306
