apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: sqldb
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: sqldb
spec:
  containers:
    - name: mysql
      image: 892915606637.dkr.ecr.us-east-1.amazonaws.com/mysql-repo-assignment2:v1.1
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: athakur28
