apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: sqldb
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 892915606637.dkr.ecr.us-east-1.amazonaws.com/mysql-repo-assignment2:v1.1
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: athakur28
