apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp
spec:
  containers:
    - name: webapp
      image: 892915606637.dkr.ecr.us-east-1.amazonaws.com/webapp-repo-assignment2:v1.1
      ports:
        - containerPort: 8080
      env:
        - name: DBPWD
          value: athakur28
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
